### PR TITLE
Feat(web-react): Add 'use client' to all components #DS-1392

### PR DESCRIPTION
**Pull request by pavelklibani**
### Issue reference

[Podpora pro React Server Components](https://jira.almacareer.tech/browse/DS-1392)

### CODE REVIEW

**Comment by literat** [comment]
Since I will be on vacation I would like to ask @vmilersky to give this a green if all will be working on the `platform-frontends` project. Thanks.

**Comment by curdaj** [comment]
Wouldn't it be good to document it somehow or mention it somewhere?

**Review by curdaj — APPROVED** [review]

**Review by literat — APPROVED** [review]
It is looking good. I have to suggest changing the commit message to something like `Mark all components as Client components`, you can also add a link to the https://react.dev/reference/rsc/use-client and mention that we want to support usage of our components alongside with RSC. Thanks :-)

**Comment by literat** [comment]
> Wouldn't it be good to document it somehow or mention it somewhere?

Maybe add some kind of badge to the package main readme file? It can be written almost everything in the badge content :-)

**Comment by pavelklibani** [comment]
> > Wouldn't it be good to document it somehow or mention it somewhere?
> 
> Maybe add some kind of badge to the package main readme file? It can be written almost everything in the badge content :-)

Badge added to readme file

**Pull request merged**
