### PR TITLE
Feat(web): Add utility classes for border radius using radii tokens

### PR DESCRIPTION
**Pull request by vmilersky**
…JALL-53

### CODE REVIEW

**Review by literat — APPROVED** [review]
LGTM

**Comment by literat** [comment]
@vmilersky Please, do not forget to update Supernova documentation as well. Or create an issue for that. See: https://spirit.supernova-docs.io/spirit/latest/development/utilities.html Thanks.

**Comment by adamkudrna** [comment]
> @vmilersky Please, do not forget to update Supernova documentation as well. Or create an issue for that. See: https://spirit.supernova-docs.io/spirit/latest/development/utilities.html Thanks.

I can do that once we agree on the utility name.

**Comment by vmilersky** [comment]
> > @vmilersky Please, do not forget to update Supernova documentation as well. Or create an issue for that. See: https://spirit.supernova-docs.io/spirit/latest/development/utilities.html Thanks.
> 
> I can do that once we agree on the utility name.

@literat I have already updated [documentation](https://spirit.supernova-docs.io/spirit/latest/development/utilities.html#section-border-radius-db) in Supernova.

Thank you, @adamkudrna for guidance and assistance.

**Pull request merged**
