### PR TITLE
Chore(ci): Remove deprecated CI configuration

### PR DESCRIPTION
**Pull request by literat**

### CODE REVIEW

**Review by adamkudrna — APPROVED** [review]
How about `bin/integrate.sh`? Isn't it also part of the old CI configuration?

**Comment by adamkudrna** [comment]
I really like this kind of PRs 🙂.

obrazek

**Comment by adamkudrna** [comment]
> How about `bin/integrate.sh`? Isn't it also part of the old CI configuration?

The same question for `.prettierignore`:

```json
// Next.JS build files
.next
```

**Comment by literat** [comment]
> How about `bin/integrate.sh`? Isn't it also part of the old CI configuration?

Yes, it is part of old CI when we had stagging env. Removing it.

**Comment by literat** [comment]
> > How about `bin/integrate.sh`? Isn't it also part of the old CI configuration?
> 
> The same question for `.prettierignore`:
> 
> ```json
> // Next.JS build files
> .next
> ```
> 
> **Edit:** Sorry, this one doesn't seem to be related with this PR. But I tried to run a few npm tasks and this directory didn't show up anyway.

In package `colors` there is a directory with example which is using Next.js to demonstrate use of this package.

**Pull request merged**
