### PR TITLE
Deps(web-twig): Freeze TwigX version until we fix the parsing regexp

### PR DESCRIPTION
**Pull request by crishpeen**
DS-659

### CODE REVIEW

**Review by literat — APPROVED** [review]

**Comment by literat** [comment]
@crishpeen It will be great if there is a link/reference to the issue in this PR or in the commit message.

**Comment by crishpeen** [comment]
> @crishpeen It will be great if there is a link/reference to the issue in this PR or in the commit message.

There is an issue number in the PR desc, but sure I can add it to the commit msg

**Comment by literat** [comment]
> > @crishpeen It will be great if there is a link/reference to the issue in this PR or in the commit message.
> 
> There is an issue number in the PR desc, but sure I can add it to the commit msg

Ok, so that is fine then. Or maybe, because GitHub creates a reference to itself the link in the commit message body will be better. Not sure. 🤷

**Comment by crishpeen** [comment]
It looks like a new version is gonna be released soon, so let's wait till that happens and then we will update this PR with the correct limits.

**Pull request merged**
