### PR TITLE
BREAKING CHANGE: Enhance the Dropdown shadow and remove its feature flag #DS-1067

### PR DESCRIPTION
**Pull request by crishpeen**

### CODE REVIEW

**Review by literat — APPROVED** [review]
LGTM 👍

Did you try running e2e tests on this PR using GitHub Actions. I do not see the label set. But the visual snapshot is updated 🤔

**Review by pavelklibani — APPROVED** [review]

**Comment by adamkudrna** [comment]
> LGTM 👍
> 
> Did you try running e2e tests on this PR using GitHub Actions. I do not see the label set. But the visual snapshot is updated 🤔

@literat In that case, could we say "run visual tests automatically whenever a snapshot is changed"? 🤔

**Review by adamkudrna — APPROVED** [review]
Cool! Maybe I'd just mention the feature flag name explicitly in the Migration Guide.

**Comment by literat** [comment]
> In that case, could we say "run visual tests automatically whenever a snapshot is changed"? 🤔

I think this is possible to have a condition in our pipeline based on changed files.

**Pull request merged**
