### PR TITLE
Deps(repo): Switch from `npm-run-all` to `npm-run-all2` fork

### PR DESCRIPTION
**Pull request by literat**
## Description

  * the original library is unmaintained for more than 5 years
  * the `npm-run-all2` is a maintenance fork

### Additional context

https://github.com/bcomnes/npm-run-all2

### CODE REVIEW

**Comment by crishpeen** [comment]
Do we plan to keep this even if it is only a maintenance fork? I understand that it is better then the non-maintained one, but I would like to know if we have a plan to move somewhere else :)

**Comment by literat** [comment]
> Do we plan to keep this even if it is only a maintenance fork? I understand that it is better then the non-maintained one, but I would like to know if we have a plan to move somewhere else :)

In this case "maintenance" means not only updates but also some development for future node compatibility and some babel issues, etc.

**Review by adamkudrna — COMMENTED** [review]
🙈

Anyway, do we use the `--parallel` flag anywhere? Because if not, I don't see a reason for using a dependency instead of writing something as simple as `yarn task1 && yarn task2`…

**Comment by literat** [comment]
> 🙈
> 
> Anyway, do we use the `--parallel` flag anywhere? Because if not, I don't see a reason for using a dependency instead of writing something as simple as `yarn task1 && yarn task2`…

**web**: `"js:compile": "npm-run-all --aggregate-output --parallel js:compile:**",`

Anyway, this is a dev dependency and it is a part of the DX. I do not want to write `yarn task1 && yarn task2`.
It can do much more like using asterisks `*` for running multiple scripts based on some kind of pattern.

**Review by pavelklibani — APPROVED** [review]

**Pull request merged**
