### PR TITLE
Demonstrate composition of `Modal` with `ScrollView`

### PR DESCRIPTION
**Pull request by adamkudrna**
obrazek

- Demonstrate the composition of `Modal` and `ScrollView`
  - web
  - Twig
  - React
- Twig: Remove unnecessary structural comments from `Modal` demos

## TODO:

- [x] Fix in Safari

### CODE REVIEW

**Review by literat — APPROVED** [review]
LGTM 👍

**Review by tomassychra — APPROVED** [review]
👌

**Comment by adamkudrna** [comment]
TODO: fix in Safari

**Review by crishpeen — APPROVED** [review]
If it works everywhere :)

**Pull request merged**
