### PR TITLE
BREAKING CHANGE: Remove dependency twig/twig for v1

### PR DESCRIPTION
**Pull request by curdaj**

### CODE REVIEW

**Review by pavelklibani — APPROVED** [review]

**Comment by literat** [comment]
Just to be sure: no updated `composer.lock`? Even in the Twig demo app? Did you try to run `composer update`? This does not mean that this PR is not correct, but I am trying to verify the change. Thanks.

**Comment by crishpeen** [comment]
> Just to be sure: no updated `composer.lock`? Even in the Twig demo app? Did you try to run `composer update`? This does not mean that this PR is not correct, but I am trying to verify the change. Thanks.

`composer update` updated all dependencies, is it ok @literat? They are still in allowed range set in composer.json, but I am not sure if we want to do that.

**Review by crishpeen — APPROVED** [review]

**Comment by literat** [comment]
Will be mergeable after this PR: https://github.com/lmc-eu/spirit-design-system/pull/1404

**Comment by literat** [comment]
> Will be mergeable after this PR: #1404. It looks like we are not ignoring lockfiles and the Composer changed the formatting of the lockfile.

This has been merged into the main. Please, rebase the entire release and this branch also.

**Pull request merged**
