### PR TITLE
Feat(web): Make `BaseComponent` available for building product design

### PR DESCRIPTION
**Pull request by literat**
system JS plugins

### CODE REVIEW

**Review by tomassychra — APPROVED** [review]

**Comment by literat** [comment]
Let's discuss:

**Do we want to make accessible all our library functions, BaseComponent and DOM manipulation?**

**PROs**
- product DSs can build their own JS plugin based on our manipulation techniques
- sharing code, those functions are not part of the products

**CONs**
- we can easily break something
- another point where we should deal with breaking changes
- make sense only for `web-twig` components

**Comment by tomassychra** [comment]
Consider not to also export `EventHandler` and similar utilities. Or deal with it [later](https://jira.lmc.cz/browse/DS-514)?

**Comment by tomassychra** [comment]
But otherwise I think it wouldn't be bad to have such things exported, maybe even as part of the new `utilities` package? Or better yet, if these utilities were shared across the entire system?

**Review by adamkudrna — APPROVED** [review]
Since we also export our Sass tooling, this sounds like a good idea to me. Of course, it's another API point we must look after once we start distributing it.

**Pull request merged**
