### PR TITLE
Docs(web-react, web-twig): Add ScrollView demo #DS-906

### PR DESCRIPTION
**Pull request by pavelklibani**
## Description

ScrollView demos are now same in all packages

## Additional info

In web demo there is also `Custom Shadows`version, but we don't have it integrated in react and twig yet.

### Issue reference

[Demo: ScrollView má ve všech technologiích stejná dema](https://jira.lmc.cz/browse/DS-906)

### CODE REVIEW

**Comment by literat** [comment]
Although it is looking good, I am missing the purple color in the **Custom shadows** section.

**Comment by literat** [comment]
> In web demo there is also Custom Shadowsversion, but we don't have it integrated in react and twig yet.

Can you add it to the unified demo CSS, please?

**Review by literat — APPROVED** [review]
LGTM 👍

**Comment by crishpeen** [comment]
> > In web demo there is also Custom Shadowsversion, but we don't have it integrated in react and twig yet.
> 
> Can you add it to the unified demo CSS, please?

we decided to add a bug issue instead

**Review by crishpeen — APPROVED** [review]

**Pull request merged**
