### PR TITLE
Fix `iconName` prop on Alert component which was passed to html element

### PR DESCRIPTION
**Pull request by literat**

### CODE REVIEW

**Comment by literat** [comment]
@crishpeen Please check https://github.com/lmc-eu/spirit-design-system/pull/699/files#diff-75d7ba5f136ec3e532794568dbf35932491b6879c34a273e975962d84022d18dR8-R11 if it is ok to use these icons as default for these colors.

**Comment by literat** [comment]
Screenshot 2023-02-15 at 12 30 03

For other colors, the default `info` icon was used.

**Comment by literat** [comment]
- [ ] Check web demo
- [ ] Check web-twig

**Review by janicekt — APPROVED** [review]

**Review by crishpeen — APPROVED** [review]
LGTM

**Pull request merged**
